-- AlterTable
ALTER TABLE "User" ADD COLUMN "address" TEXT;
ALTER TABLE "User" ADD COLUMN "city" TEXT;
ALTER TABLE "User" ADD COLUMN "criminalRecord" TEXT;
ALTER TABLE "User" ADD COLUMN "dateOfBirth" DATETIME;
ALTER TABLE "User" ADD COLUMN "drugReport" TEXT;
ALTER TABLE "User" ADD COLUMN "formalPhoto" TEXT;
ALTER TABLE "User" ADD COLUMN "licenseDocument" TEXT;
ALTER TABLE "User" ADD COLUMN "licenseNumber" TEXT;
ALTER TABLE "User" ADD COLUMN "phone" TEXT;
ALTER TABLE "User" ADD COLUMN "pincode" TEXT;
ALTER TABLE "User" ADD COLUMN "state" TEXT;
